### ISSUE TITLE
Scaling model error : FileNotFoundError:

### ISSUE THREAD

**Issue by annatudse** [hmok/OpenColab#2]
hi 
I ran the two cells below code cell 27 + 28 without any luck as noted in the comment. Its openColab-v4.4.ipnyb. I ran it directly from github on my colab. I tried to copy the ipnyb file into my google drive before running previously but I got the same error. 

![image](https://user-images.githubusercontent.com/102486735/222405143-d59b2bff-b9c1-422b-ab6f-86ac0289552c.png)

Kind regards Anna

**Comment by hmok** [comment]
Thanks for  your questions. As you can see in the paranthesis you need to run these two lines before you run scaling:
osim.Logger_setLevel(0)
osim.Logger.addFileSink()

Then run the Scaling Validation to get the outcomes like see below:
![image](https://user-images.githubusercontent.com/8562198/222630331-69700628-f3b0-4c89-bc85-b9948c6a34a8.png)
